language: java
jdk: oraclejdk8
dist: trusty
deploy:
  provider: heroku
  api_key:
    secure: kxAGKRUQPKmtoKB5YCYfGFBsZCbCLztxErpsrgL2+kqM7eLzAPKlf+yk4hMfdEZL32FMK/AJi16af34HI/9utmxY14bmjwFSf2z99lXtqSbSXE8BAjiGTRF7MTJC2gWV3Hg7scmj3tS9WwWg8FE5D0cVsmeBMMV9I0BuFjHjOQmqgZbqbHkL/Wt14ds0bKB1V3R62XRKPsI4+EI2mJRMTXoOoqtiiL0M8ECWNafQjzSKgRaM+ZzoVZGfXhnbYed9t/9PfmGT4Jy5N9Jb6hoO/mSA7PWN52yCYy1Dv2tfAuxSFLMiU925H7cj6KFrDe3Wt2YupgQ8QTt/6ubBrmLHvFOaRc0E5Gs6LJ0UXgBWlaAPkxJpoV5DXUsOepX9zY5kCwftnhrbRAgcdfrZFXD9YwB73s0Qvdu4vN0DKUc2127om4MABUQ+fIov9xf9grhYuEwJ12C5SyFp3KX13rK6+CY7DGeg5yTw9FFi42QG7IYzAPb04UTU/psz2SV+eoXnhRBT8LFNaLWy62zglgaueR4whDPtqQgL0z8o0KI9sjaTEDtJWLVkDfg2yWj0G7uR/Z5Tnfxyp+AqtiKvOsLH+7QUPOGPuUmWMjAZyQGX/bDMIbCcX9SAAcMF5Jh1l2UQANvcDQ0ETfrydOaXyL1tMsFj1UBv40jni6cjlSKLOPM=
  app: isticcontactos
